# 服务器设置(config.toml)，配置文件放在被扫描的根目录中，或$HOME/config/comigo.可以用“comi --generate-config”生成本示例文件
 # 提供阅读服务的端口
Port = 1234
# 自定义二维码显示的主机名
Host = ''
# 设置默认扫描的书库文件夹
StoresPath = ['C:\test\Comic', 'D:\some_path\book']
# 最大扫描深度
MaxDepth = 3
# 访问限制：用户名。需要设置密码
UserName = 'admin'
# 访问限制：密码。需要设置用户名。
Password = ''
# Https证书，同时设置KeyFile则启用HTTPS协议
CertFile = ''
# Https证书，同时设置CertFile则启用HTTPS协议
KeyFile = ''
# 是否同时打开浏览器，windows默认true，其他默认false
OpenBrowser = false
# 只在本机localhost提供服务，不对外共享
DisableLAN = false
# 是否保存web图片缓存，可以加快二次读取，但会占用硬盘空间
CacheFileEnable = true
# web图片缓存存储位置，默认系统临时文件夹
CacheFilePath = '.comigo'
# 退出的时候，清理web图片缓存
CacheFileClean = false
# 需要排除的文件或文件夹
ExcludeFileOrFolders = ['.comigo', '.idea', '.vscode', '.git', 'node_modules', 'flutter_ui', '.local/share/Trash', '$RECYCLE.BIN', 'Config.Msi', 'System Volume Information', '.sys', ' .DS_Store', '.dll', '.log', '.cache', '.exe']
# 需要扫描的图片文件后缀
SupportMediaType = ['.jpg', '.jpeg', '.jpe', '.jpf', '.jfif', '.jfi', '.png', '.bmp', '.webp', '.ico', '.heic', '.avif']
# 需要扫描的图书文件后缀
SupportFileType = ['.zip', '.tar', '.rar', '.cbr', '.cbz', '.epub', '.tar.gz', '.tgz', '.tar.bz2', '.tbz2', '.tar.xz', '.txz', '.tar.lz4', '.tlz4', '.tar.sz', '.tsz', '.bz2', '.gz', '.lz4', '.sz', '.xz', '.pdf', '.mp4', '.webm']
# 压缩包或文件夹内，至少有几张图片，才算作书籍
MinImageNum = 1
# 打印所有可能可用的地址的二维码
PrintAllIP = false
# 开启Debug模式
Debug = false
# 记录Log到本地文件
LogToFile = false
# Log保存的位置
LogFilePath = ''
# Log文件名
LogFileName = 'comigo.log'
# 非utf-8编码的ZIP文件，尝试哪一种编码，默认GBK
ZipFileTextEncoding = 'gbk'
# 后台启动FrpClient
EnableFrpcServer = false
# FrpClient设置
[FrpConfig]
# 手动设定frpc可执行程序的路径,默认为frpc
FrpcCommand = 'frpc'
ServerAddr = 'frps.example.com'
ServerPort = 7000
Token = 'token_secret_sample'
FrpType = 'tcp'
RemotePort = 50000
RandomRemotePort = true

