CheckImage = false
CleanAllTempFile = true
CleanAllTempFileOnExit = false
Debug = false
DisableLAN = false
EnableFrpcServer = false
EnableWebpServer = false
Host = ""
LogFileName = "comigo.log"
LogFilePath = "C:\\Users\\bai"
LogToFile = false
MaxDepth = 2
MinImageNum = 1
GenerateConfig = false
OpenBrowser = true
Password = ""
Port = 1234
PrintAllIP = false
SketchCountSeconds = 90
SortImage = "none"
TempPATH = ""
Template = "scrool"
UserName = "comi"
ZipFilenameEncoding = ""

[FrpConfig]
  FrpType = "tcp"
  FrpcCommand = "frpc"
  RandomRemotePort = true
  RemotePort = 50000
  ServerAddr = "frps.example.com"
  ServerPort = 7000
  Token = "token_secretSAMPLE"

[WebpConfig]
  AllowedTypes = [".jpg", ".jpeg", ".JPEG", ".jpe", ".jpf", ".jfif", ".jfi", ".png", ".bmp"]
  ExhaustPath = ""
  HOST = "127.0.0.1"
  ImgPath = ""
  PORT = "3333"
  QUALITY = 70
  WebpCommand = "webp-server"
