Auth = ""
CheckImage = true
CleanAllTempFile = true
CleanAllTempFileOnExit = false
Debug = false
DisableLAN = false
EnableFrpcServer = false
EnableWebpServer = false
Host = ""
LogFileName = "comigo.log"
LogFilePath = ""
LogToFile = false
MaxDepth = 1
MinImageNum = 1
NewConfig = true
OpenBrowser = true
Port = 12345
PrintAllIP = false
SketchCountSeconds = 90
SortImage = "none"
TempPATH = ""
Template = "scroll"
ZipFilenameEncoding = ""

[FrpConfig]
  FrpType = "tcp"
  FrpcCommand = "frpc"
  RandomRemotePort = true
  RemotePort = 50000
  ServerAddr = "frps.example.com"
  ServerPort = 7000
  Token = "token_secretSAMPLE"

[WebpConfig]
  AllowedTypes = [".jpg", ".jpeg", ".JPEG", ".jpe", ".jpf", ".jfif", ".jfi", ".png", ".bmp"]
  ExhaustPath = ""
  HOST = "127.0.0.1"
  ImgPath = ""
  PORT = "3333"
  QUALITY = 85
  WebpCommand = "webp-server"
