# goreleaser release --snapshot --clean
project_name: comigo
release:
  draft: true

# https://goreleaser.com/customization/hooks/
#before:
#  hooks:
    # You may remove this if you don't use go modules.
    # - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

# Default: './dist'
dist: bin

checksum:
  # You can change the name of the checksums file.
  #
  # Default: {{ .ProjectName }}_{{ .Version }}_checksums.txt
  # Templates: allowed
  name_template: "checksums.txt"

  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  #
  # Default: sha256.
  algorithm: sha256

builds:
  - goos:
      - linux
      - darwin
    binary: comi
    # https://goreleaser.com/customization/builds/#build-hooks
    hooks:
      pre:
        - go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        # - go generate
      post:
        - rm -rf bin/comigo_darwin_amd64_v1
        - rm -rf bin/comigo_darwin_arm64
        - rm -rf bin/comigo_linux_386
        - rm -rf bin/comigo_linux_amd64_v1
        - rm -rf bin/comigo_linux_arm64
    ldflags:
      - -s -w -X $controllers.Version=$VERSION
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
