# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
## go install github.com/cosmtrek/air@latest

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/comigo ./comigo.go"
# Binary file yields from `cmd`.
bin = "tmp/comigo"
# Customize binary, can setup environment variables when run your app.
# full_bin = "COMI_DEBUG_MODE=true COMI_MIN_MEDIA_NUM=2 ./tmp/main test --max-depth=5"
# Watch these filename extensions.
include_ext = ["go", "rar","zip","cbr","cbz","tpl", "tmpl", "html"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", ".idea",".git", ".vscode", ".cache"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = ["_test.go",]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# This log file places in your tmp_dir.
log = "build-errors.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
kill_delay = "0s"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = true
rerun_delay = 500
send_interrupt = false
stop_on_error = false
